name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 7.4
          - '8.0'
          - 8.1
        typo3:
          - ^10.4
          - ^11.5
        exclude:
          - php: '8.0'
            typo3: ^10.4
          - php: 8.1
            typo3: ^10.4
            

    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          PHP_VERSION: ${{matrix.php}}
          TYPO3_VERSION: ${{matrix.typo3}}
        run: docker-compose run --rm app composer build

      - name: Cleanup
        if: ${{ always() }}
        run: docker-compose down --volumes

  release-ter:
    name: TYPO3 TER release

    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to TER
        env:
          TYPO3_ORG_USERNAME: ${{secrets.TYPO3_ORG_USERNAME}}
          TYPO3_ORG_PASSWORD: ${{secrets.TYPO3_ORG_PASSWORD}}
        run: docker-compose run --rm app composer deploy:ter
